import mongoose from "mongoose";

const planningSchema = new mongoose.Schema({
    code:{
        type:String,
    },
    starttime:{
        type:String,
    },
    endtime:{
        type:String,
    },
    orderdate:{
        type:String,
    },
    lotno:{
        type:String,
    },
    colourcode:{
        type:String,
    },
    material:{
        type:String,
    },
    totalorder:{
        type:Number,
    },
    totaloutput:{
        type:Number,
        default:0
    },
    reject:{
        type:Number,
        default:0
    },
    cause:{
        type:String,
    },
    startup:{
        type:Number,
        default:0
    },
    screwout:{
        type:Number,
        default:0
    },
    processcomplication:{
        type:Number,
        default:0
    },
    qctime:{
        type:Number,
        default:0
    },
    downtime:{
        type:Number,
        default:0
    },
    reason:{
        type:String,
    },
    washresin:{
        type:String,
    },
    washup:{
        type:Number,
        default:0
    },
    stranddrop:{
        type:Number,
        default:0
    },
    qcinspect:{
        type:Number,
        default:0
    },
    whiteoil:{
        type:Number,
        default:0
    },
    vent:{
        type:Number,
        default:0
    },
    unevenpallet:{
        type:Number,
        default:0
    },
    trialrun:{
        type:Number,
        default:0
    },
    wastage:{
        type:Number,
        default:0
    },
    meterstart:{
        type:Number,
        default:0
    },
    meterend:{
        type:Number,
        default:0
    },
    totalmeter:{
        type:Number,
        default:0
    },
    color:{
        type:String,
    },
    density:{
        type:Number,
    },
    operator:{
        type:String,
    },
    irr:{
        type:Number,
        default:0
    },
    arr:{
        type:Number,
        default:0
    },
    ipqc:{
        type:Number,
        default:0
    },
    setup:{
        type:Number,
        default:0
    },
    prodleadtime:{
        type:Number,
        default:0
    },
    planprodtime:{
        type:Number,
        default:0
    },
    operatingtime:{
        type:Number,
        default:0
    },
    availability:{
        type:Number,
        default:0
    },
    performance:{
        type:Number,
        default:0
    },
    quality:{
        type:Number,
        default:0
    },
    oee:{
        type:Number,
        default:0
    }
},{timestamps:true})

const Planning = mongoose.model('Planning', planningSchema)

export default Planning